// Code generated by protoc-gen-gogo.
// source: internal/data.proto
// DO NOT EDIT!

/*
Package internal is a generated protocol buffer package.

It is generated from these files:
	internal/data.proto

It has these top-level messages:
	WriteShardRequest
	From
	Content
	Mention
	Message
	WriteShardResponse
	MapShardRequest
	MapShardResponse
*/
package internal

import proto "github.com/gogo/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type WriteShardRequest struct {
	ShardID          *uint64    `protobuf:"varint,1,req" json:"ShardID,omitempty"`
	Messages         []*Message `protobuf:"bytes,2,rep" json:"Messages,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *WriteShardRequest) Reset()         { *m = WriteShardRequest{} }
func (m *WriteShardRequest) String() string { return proto.CompactTextString(m) }
func (*WriteShardRequest) ProtoMessage()    {}

func (m *WriteShardRequest) GetShardID() uint64 {
	if m != nil && m.ShardID != nil {
		return *m.ShardID
	}
	return 0
}

func (m *WriteShardRequest) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type From struct {
	UserID           *string `protobuf:"bytes,1,req" json:"UserID,omitempty"`
	Name             *string `protobuf:"bytes,2,req" json:"Name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *From) Reset()         { *m = From{} }
func (m *From) String() string { return proto.CompactTextString(m) }
func (*From) ProtoMessage()    {}

func (m *From) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *From) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type Content struct {
	PlainText        *string `protobuf:"bytes,1,req" json:"PlainText,omitempty"`
	HTML             *string `protobuf:"bytes,2,opt" json:"HTML,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}

func (m *Content) GetPlainText() string {
	if m != nil && m.PlainText != nil {
		return *m.PlainText
	}
	return ""
}

func (m *Content) GetHTML() string {
	if m != nil && m.HTML != nil {
		return *m.HTML
	}
	return ""
}

type Mention struct {
	RecipientID       *string `protobuf:"bytes,1,req" json:"RecipientID,omitempty"`
	RecipientUsername *string `protobuf:"bytes,2,req" json:"RecipientUsername,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *Mention) Reset()         { *m = Mention{} }
func (m *Mention) String() string { return proto.CompactTextString(m) }
func (*Mention) ProtoMessage()    {}

func (m *Mention) GetRecipientID() string {
	if m != nil && m.RecipientID != nil {
		return *m.RecipientID
	}
	return ""
}

func (m *Mention) GetRecipientUsername() string {
	if m != nil && m.RecipientUsername != nil {
		return *m.RecipientUsername
	}
	return ""
}

type Message struct {
	Id               *string  `protobuf:"bytes,1,opt" json:"Id,omitempty"`
	Time             *int64   `protobuf:"varint,2,req" json:"Time,omitempty"`
	From             *From    `protobuf:"bytes,3,opt" json:"From,omitempty"`
	Content          *Content `protobuf:"bytes,4,opt" json:"Content,omitempty"`
	Mentions         *Mention `protobuf:"bytes,5,opt" json:"Mentions,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}

func (m *Message) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Message) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *Message) GetFrom() *From {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Message) GetContent() *Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Message) GetMentions() *Mention {
	if m != nil {
		return m.Mentions
	}
	return nil
}

type WriteShardResponse struct {
	Code             *int32  `protobuf:"varint,1,req" json:"Code,omitempty"`
	Message          *string `protobuf:"bytes,2,opt" json:"Message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WriteShardResponse) Reset()         { *m = WriteShardResponse{} }
func (m *WriteShardResponse) String() string { return proto.CompactTextString(m) }
func (*WriteShardResponse) ProtoMessage()    {}

func (m *WriteShardResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *WriteShardResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type MapShardRequest struct {
	ShardID          *uint64 `protobuf:"varint,1,req" json:"ShardID,omitempty"`
	Query            *string `protobuf:"bytes,2,req" json:"Query,omitempty"`
	ChunkSize        *int32  `protobuf:"varint,3,req" json:"ChunkSize,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MapShardRequest) Reset()         { *m = MapShardRequest{} }
func (m *MapShardRequest) String() string { return proto.CompactTextString(m) }
func (*MapShardRequest) ProtoMessage()    {}

func (m *MapShardRequest) GetShardID() uint64 {
	if m != nil && m.ShardID != nil {
		return *m.ShardID
	}
	return 0
}

func (m *MapShardRequest) GetQuery() string {
	if m != nil && m.Query != nil {
		return *m.Query
	}
	return ""
}

func (m *MapShardRequest) GetChunkSize() int32 {
	if m != nil && m.ChunkSize != nil {
		return *m.ChunkSize
	}
	return 0
}

type MapShardResponse struct {
	Code             *int32  `protobuf:"varint,1,req" json:"Code,omitempty"`
	Message          *string `protobuf:"bytes,2,opt" json:"Message,omitempty"`
	Data             []byte  `protobuf:"bytes,3,opt" json:"Data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MapShardResponse) Reset()         { *m = MapShardResponse{} }
func (m *MapShardResponse) String() string { return proto.CompactTextString(m) }
func (*MapShardResponse) ProtoMessage()    {}

func (m *MapShardResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MapShardResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *MapShardResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
}
