// Code generated by protoc-gen-gogo.
// source: internal/data.proto
// DO NOT EDIT!

/*
Package internal is a generated protocol buffer package.

It is generated from these files:
	internal/data.proto

It has these top-level messages:
	WriteShardRequest
	From
	Content
	Mention
	Field
	Tag
	Message
	WriteShardResponse
	MapShardRequest
	MapShardResponse
*/
package internal

import proto "github.com/gogo/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type WriteShardRequest struct {
	ShardID          *uint64    `protobuf:"varint,1,req" json:"ShardID,omitempty"`
	Messages         []*Message `protobuf:"bytes,2,rep" json:"Messages,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *WriteShardRequest) Reset()         { *m = WriteShardRequest{} }
func (m *WriteShardRequest) String() string { return proto.CompactTextString(m) }
func (*WriteShardRequest) ProtoMessage()    {}

func (m *WriteShardRequest) GetShardID() uint64 {
	if m != nil && m.ShardID != nil {
		return *m.ShardID
	}
	return 0
}

func (m *WriteShardRequest) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type From struct {
	UserID           *string `protobuf:"bytes,1,req" json:"UserID,omitempty"`
	Name             *string `protobuf:"bytes,2,req" json:"Name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *From) Reset()         { *m = From{} }
func (m *From) String() string { return proto.CompactTextString(m) }
func (*From) ProtoMessage()    {}

func (m *From) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *From) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type Content struct {
	PlainText        *string `protobuf:"bytes,1,req" json:"PlainText,omitempty"`
	HTML             *string `protobuf:"bytes,2,opt" json:"HTML,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}

func (m *Content) GetPlainText() string {
	if m != nil && m.PlainText != nil {
		return *m.PlainText
	}
	return ""
}

func (m *Content) GetHTML() string {
	if m != nil && m.HTML != nil {
		return *m.HTML
	}
	return ""
}

type Mention struct {
	RecipientID       *string `protobuf:"bytes,1,req" json:"RecipientID,omitempty"`
	RecipientUsername *string `protobuf:"bytes,2,req" json:"RecipientUsername,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *Mention) Reset()         { *m = Mention{} }
func (m *Mention) String() string { return proto.CompactTextString(m) }
func (*Mention) ProtoMessage()    {}

func (m *Mention) GetRecipientID() string {
	if m != nil && m.RecipientID != nil {
		return *m.RecipientID
	}
	return ""
}

func (m *Mention) GetRecipientUsername() string {
	if m != nil && m.RecipientUsername != nil {
		return *m.RecipientUsername
	}
	return ""
}

type Field struct {
	Name             *string  `protobuf:"bytes,1,req" json:"Name,omitempty"`
	Int32            *int32   `protobuf:"varint,2,opt" json:"Int32,omitempty"`
	Int64            *int64   `protobuf:"varint,3,opt" json:"Int64,omitempty"`
	Float64          *float64 `protobuf:"fixed64,4,opt" json:"Float64,omitempty"`
	Bool             *bool    `protobuf:"varint,5,opt" json:"Bool,omitempty"`
	String_          *string  `protobuf:"bytes,6,opt" json:"String,omitempty"`
	Bytes            []byte   `protobuf:"bytes,7,opt" json:"Bytes,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}

func (m *Field) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Field) GetInt32() int32 {
	if m != nil && m.Int32 != nil {
		return *m.Int32
	}
	return 0
}

func (m *Field) GetInt64() int64 {
	if m != nil && m.Int64 != nil {
		return *m.Int64
	}
	return 0
}

func (m *Field) GetFloat64() float64 {
	if m != nil && m.Float64 != nil {
		return *m.Float64
	}
	return 0
}

func (m *Field) GetBool() bool {
	if m != nil && m.Bool != nil {
		return *m.Bool
	}
	return false
}

func (m *Field) GetString_() string {
	if m != nil && m.String_ != nil {
		return *m.String_
	}
	return ""
}

func (m *Field) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

type Tag struct {
	Key              *string `protobuf:"bytes,1,req" json:"Key,omitempty"`
	Value            *string `protobuf:"bytes,2,req" json:"Value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}

func (m *Tag) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Tag) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type Message struct {
	Id               *string  `protobuf:"bytes,1,opt" json:"Id,omitempty"`
	Time             *int64   `protobuf:"varint,2,req" json:"Time,omitempty"`
	Fields           []*Field `protobuf:"bytes,3,rep" json:"Fields,omitempty"`
	Tags             []*Tag   `protobuf:"bytes,4,rep" json:"Tags,omitempty"`
	From             *From    `protobuf:"bytes,5,opt" json:"From,omitempty"`
	Content          *Content `protobuf:"bytes,6,opt" json:"Content,omitempty"`
	Mentions         *Mention `protobuf:"bytes,7,opt" json:"Mentions,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}

func (m *Message) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Message) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *Message) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *Message) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Message) GetFrom() *From {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Message) GetContent() *Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Message) GetMentions() *Mention {
	if m != nil {
		return m.Mentions
	}
	return nil
}

type WriteShardResponse struct {
	Code             *int32  `protobuf:"varint,1,req" json:"Code,omitempty"`
	Message          *string `protobuf:"bytes,2,opt" json:"Message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WriteShardResponse) Reset()         { *m = WriteShardResponse{} }
func (m *WriteShardResponse) String() string { return proto.CompactTextString(m) }
func (*WriteShardResponse) ProtoMessage()    {}

func (m *WriteShardResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *WriteShardResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type MapShardRequest struct {
	ShardID          *uint64 `protobuf:"varint,1,req" json:"ShardID,omitempty"`
	Query            *string `protobuf:"bytes,2,req" json:"Query,omitempty"`
	ChunkSize        *int32  `protobuf:"varint,3,req" json:"ChunkSize,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MapShardRequest) Reset()         { *m = MapShardRequest{} }
func (m *MapShardRequest) String() string { return proto.CompactTextString(m) }
func (*MapShardRequest) ProtoMessage()    {}

func (m *MapShardRequest) GetShardID() uint64 {
	if m != nil && m.ShardID != nil {
		return *m.ShardID
	}
	return 0
}

func (m *MapShardRequest) GetQuery() string {
	if m != nil && m.Query != nil {
		return *m.Query
	}
	return ""
}

func (m *MapShardRequest) GetChunkSize() int32 {
	if m != nil && m.ChunkSize != nil {
		return *m.ChunkSize
	}
	return 0
}

type MapShardResponse struct {
	Code             *int32   `protobuf:"varint,1,req" json:"Code,omitempty"`
	Message          *string  `protobuf:"bytes,2,opt" json:"Message,omitempty"`
	Data             []byte   `protobuf:"bytes,3,opt" json:"Data,omitempty"`
	TagSets          []string `protobuf:"bytes,4,rep" json:"TagSets,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MapShardResponse) Reset()         { *m = MapShardResponse{} }
func (m *MapShardResponse) String() string { return proto.CompactTextString(m) }
func (*MapShardResponse) ProtoMessage()    {}

func (m *MapShardResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *MapShardResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *MapShardResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MapShardResponse) GetTagSets() []string {
	if m != nil {
		return m.TagSets
	}
	return nil
}

func init() {
}
